// <auto-generated />
using MiNegocio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiNegocio.Api.Migrations
{
    [DbContext(typeof(MiNegocioDbContext))]
    [Migration("20261005051540_SeedCategorias")]
    partial class SeedCategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiNegocio.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Camisas",
                            Prefijo = "CAM"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Blusas",
                            Prefijo = "BLU"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Pantalones",
                            Prefijo = "PAN"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Enaguas",
                            Prefijo = "ENA"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Vestidos",
                            Prefijo = "VES"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Zapatos",
                            Prefijo = "ZAP"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Gorras y sombreros",
                            Prefijo = "GOR"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Trajes de baño",
                            Prefijo = "TRA"
                        });
                });

            modelBuilder.Entity("MiNegocio.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("MiNegocio.Api.Models.Producto", b =>
                {
                    b.HasOne("MiNegocio.Api.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
